Refactor script to run arbitrary formatter command

diff --git a/json-formatter/go/scripts/test-messages b/json-formatter/go/scripts/test-messages
--- a/json-formatter/go/scripts/test-messages
+++ b/json-formatter/go/scripts/test-messages
@@ -1,46 +1,62 @@
 #!/usr/bin/env bash
 #
-# Runs the formatter against a list of NDJSON files and writes the output
-# next to each file
+# Iterates over a list of NDJSON files and pipes it into a command. The STDOUT
+# and STDERR is written to a file whose name is derived from the base name of 
+# the input file.
 #
-# Example: bash-4.4$ ./scripts/test-messages -o target ../../compatibility-kit/javascript/features/**/*.ndjson
+# This script is used to verify that a message consumer (formatter) is able to
+# process messages generated by a Cucumber implementation.
+#
+# Examples: 
+#  ./scripts/test-messages -e .html -o /tmp -c "./scripts/cucumber-html-formatter" ../../compatibility-kit/javascript/features/**/*.ndjson
+#  ./scripts/test-messages -e .json -o /tmp -c "./scripts/cucumber-json-formatter" ../../compatibility-kit/javascript/features/**/*.ndjson
+set -uf
 GREEN='\033[0;32m'
 RED='\033[0;31m'
 NC='\033[0m'
 
-OS=$([[ "$(uname)" == "Darwin" ]] && echo "darwin" || echo "linux")
-# Determine if we're on 386 or amd64 (ignoring other processors as we're not building on them)
-ARCH=$([[ "$(uname -m)" == "x86_64" ]] && echo "amd64" || echo "386")
-EXE="./dist/cucumber-json-formatter-${OS}-${ARCH}"
-
-while getopts "o:" option; do
+while getopts "o:c:e:" option; do
   case "${option}" in
   o)
     outdir=${OPTARG}
     ;;
+  c)
+    command=${OPTARG}
+    ;;
+  e)
+    extension=${OPTARG}
+    ;;
   *)
+    echo "Error :-("
     exit 1;
     ;;
   esac
 done
 shift $((OPTIND - 1))
 if [ -z "${outdir}" ]; then
-    echo "missing -o"
-    exit 1;
+  echo "missing -o"
+  exit 1;
+fi
+if [ -z "${command}" ]; then
+  echo "missing -c"
+  exit 1;
+fi
+if [ -z "${extension}" ]; then
+  echo "missing -e"
+  exit 1;
 fi
 
 exitstatus=0
-
 for ndjson in $*; do
   name="${outdir}/$(basename "${ndjson}")"
-  stdout="${name}.json-formatter.json"
-  stderr="${name}.json-formatter.err.txt"
-  output=$($EXE --format ndjson 2>"${stderr}" >"${stdout}" <${ndjson})
+  stdout="${name}${extension}"
+  stderr="${name}${extension}.err.txt"
+  output=$(${command} < "${ndjson}" 2> "${stderr}" > "${stdout}")
 
   if [ $? = 0 ]; then
-    echo -e "${GREEN}[v]${NC} $ndjson"
+    echo -e "${GREEN}[v]${NC} ${ndjson}"
   else
-    echo -e "${RED}[x]${NC} $ndjson"
+    echo -e "${RED}[x]${NC} ${ndjson}"
     exitstatus=1
   fi
 done
